/* The copy shop.js and product.js print.

   GENERATED by /admin/edit — every save rewrites this file whole. Editing it
   by hand works, but keep the shape: one assignment, one flat object of dotted
   keys to strings. The server parses this file, and it parses it by trusting
   that shape.

   Strings that appear in the markup are NOT here; they are in shop.html and
   product.html, where you can see them. See lib/copy.js. */

window.MERLOW_COPY = {
  "shop.empty": "The shop is being stocked — check back soon.",
  "shop.error": "Couldn’t load the shop right now — refresh to try again.",
  "product.colour": "Colour",
  "product.size": "Size",
  "product.add": "Add to cart",
  "product.note": "Made to order, usually printed within 3–7 days. Postage is worked out from your country in the cart.",
  "product.priceFrom": "from",
  "product.specBrand": "Brand",
  "product.specModel": "Model",
  "product.specType": "Type",
  "product.choose": "Choose {what}",
  "product.missingColour": "a colour",
  "product.missingSize": "a size",
  "product.missingJoin": "and",
  "product.unavailable": "Currently unavailable",
  "product.sizeUnavailable": "Not available in this colour",
  "product.imageNav": "View image {n} of {total}"
};
