'use strict';

/* Every string on /shop and /shop/:id that an admin may change.
   lib/copy.js

   ── One home per string, and no defaults table ────────────────────────────

   VANCE-HQ keeps defaults in code and overrides in a database, and spends a
   good deal of lib/content.js keeping the two from forking. There is no
   database here — the editor commits — so the fork cannot happen, and the
   simpler arrangement is available: every string lives in exactly ONE file,
   and that file is the one the site serves.

     a string you can see in the markup   →   shop.html / product.html
     a string a script prints             →   js/copy.js

   The schema below says which, for each key. It does NOT hold the values.
   Nothing in this repo holds a second copy of a string, so nothing can drift
   out of step with the page.

   ── js/copy.js is machine-written, and that is what makes it parseable ────

   It is a plain browser script, loaded by an ordinary <script> tag before
   shop.js and product.js — no fetch, no build step, no async ordering to get
   wrong. The server reads the same file by finding the object and parsing it
   as JSON, which is only safe because the file is never written by hand: the
   save endpoint rewrites it whole, in this exact shape, every time.
   test/copy.test.js is what keeps that promise honest.
*/

const HEADER = `/* The copy shop.js and product.js print.

   GENERATED by /admin/edit — every save rewrites this file whole. Editing it
   by hand works, but keep the shape: one assignment, one flat object of dotted
   keys to strings. The server parses this file, and it parses it by trusting
   that shape.

   Strings that appear in the markup are NOT here; they are in shop.html and
   product.html, where you can see them. See lib/copy.js. */
`;

const OPEN = 'window.MERLOW_COPY = ';

/* ── Limits ────────────────────────────────────────────────────────────────
   Generous enough that no honest edit hits one, small enough that a page of
   copy cannot quietly become somewhere to keep something else. */
const LIMITS = { label: 40, line: 120, para: 400, title: 70, meta: 200, url: 500 };

/**
 * What is editable.
 *
 * `where` names the file that HOLDS the string, which is also what tells the
 * save endpoint which files a given edit has to rewrite.
 *
 * `group` and `label` are for the panel in the editor that lists the strings
 * you cannot see on screen — an error message, an empty shop, a page title.
 * A string nobody can point at still has to be editable somehow, and a field
 * with no label is a field nobody can identify.
 */
const SCHEMA = [
  /* ── index.html ────────────────────────────────────────────────────────────
     The record's own words. NOT the tracklist: who is on the album and what
     genre they sang it in is a fact about the record that lives in js/main.js
     next to the YouTube id it has to change with, the same way lib/estate.js
     owns HQ's inventory. What the record is CALLED is copy; who is on it is
     not. */
  { key: 'home.pageTitle',       where: 'index.html', max: LIMITS.title, group: 'Home page, details you cannot see', label: 'Browser tab and search-result title' },
  { key: 'home.metaDescription', where: 'index.html', max: LIMITS.meta,  group: 'Home page, details you cannot see', label: 'Search-result description' },
  { key: 'home.ogTitle',         where: 'index.html', max: LIMITS.title, group: 'Home page, details you cannot see', label: 'Title when the page is shared' },
  { key: 'home.ogDescription',   where: 'index.html', max: LIMITS.meta,  group: 'Home page, details you cannot see', label: 'Description when the page is shared' },

  { key: 'home.heroEyebrow',  where: 'index.html', max: LIMITS.label },
  { key: 'home.heroPlank',    where: 'index.html', max: LIMITS.label },
  { key: 'home.heroCta',      where: 'index.html', max: LIMITS.label },
  { key: 'home.heroScroll',   where: 'index.html', max: LIMITS.label },

  { key: 'home.chorusEyebrow', where: 'index.html', max: LIMITS.label },
  { key: 'home.chorusWord1',   where: 'index.html', max: LIMITS.label },
  { key: 'home.chorusAnswer1', where: 'index.html', max: LIMITS.line },
  { key: 'home.chorusWord2',   where: 'index.html', max: LIMITS.label },
  { key: 'home.chorusAnswer2', where: 'index.html', max: LIMITS.line },
  { key: 'home.chorusWord3',   where: 'index.html', max: LIMITS.label },
  { key: 'home.chorusAnswer3', where: 'index.html', max: LIMITS.line },
  { key: 'home.chorusStanding', where: 'index.html', max: LIMITS.line },
  { key: 'home.chorusFalling',  where: 'index.html', max: LIMITS.line },
  { key: 'home.chorusNote',     where: 'index.html', max: LIMITS.line },
  { key: 'home.chorusCredit',   where: 'index.html', max: LIMITS.line },

  { key: 'home.storyEyebrow', where: 'index.html', max: LIMITS.label },
  { key: 'home.storyHeading', where: 'index.html', max: LIMITS.line },
  { key: 'home.band1Heading', where: 'index.html', max: LIMITS.line },
  { key: 'home.band1Body',    where: 'index.html', max: LIMITS.para },
  { key: 'home.band2Heading', where: 'index.html', max: LIMITS.line },
  { key: 'home.band2Body',    where: 'index.html', max: LIMITS.para },
  { key: 'home.band3Heading', where: 'index.html', max: LIMITS.line },
  { key: 'home.band3Body',    where: 'index.html', max: LIMITS.para },
  { key: 'home.factTracks',   where: 'index.html', max: LIMITS.label },
  { key: 'home.factArtists',  where: 'index.html', max: LIMITS.label },
  { key: 'home.factSongs',    where: 'index.html', max: LIMITS.label },
  { key: 'home.albumCta1',    where: 'index.html', max: LIMITS.label },
  { key: 'home.albumCta2',    where: 'index.html', max: LIMITS.label },

  { key: 'home.featuredEyebrow', where: 'index.html', max: LIMITS.label },
  { key: 'home.featuredCta',     where: 'index.html', max: LIMITS.line },

  { key: 'home.tracksEyebrow', where: 'index.html', max: LIMITS.label },
  { key: 'home.tracksHeading', where: 'index.html', max: LIMITS.line },
  { key: 'home.tracksLede',    where: 'index.html', max: LIMITS.para },

  { key: 'home.shopEyebrow', where: 'index.html', max: LIMITS.label },
  { key: 'home.shopHeading', where: 'index.html', max: LIMITS.line },
  { key: 'home.shopLede',    where: 'index.html', max: LIMITS.para },
  { key: 'home.shopCta',     where: 'index.html', max: LIMITS.label },

  { key: 'home.footTitle',   where: 'index.html', max: LIMITS.label },
  { key: 'home.footBlurb',   where: 'index.html', max: LIMITS.line },
  { key: 'home.footListH',   where: 'index.html', max: LIMITS.label },
  { key: 'home.footListLabel', where: 'index.html', max: LIMITS.label },
  { key: 'home.footListBtn', where: 'index.html', max: LIMITS.label },
  { key: 'home.footListNote', where: 'index.html', max: LIMITS.line },
  { key: 'home.footSocialH', where: 'index.html', max: LIMITS.label },
  { key: 'home.footRights',  where: 'index.html', max: LIMITS.line },
  { key: 'home.footTag',     where: 'index.html', max: LIMITS.label },

  { key: 'home.shopLoading', where: 'index.html', max: LIMITS.line,
    group: 'Home page, details you cannot see', label: 'While the shop preview is loading' },

  /* Each of these keys is on TWO elements — the button at the top of the hero
     and the matching one in the footer — because it is one fact about the band
     that happens to be printed twice. Writing it rewrites both, which is the
     whole reason they share a key rather than having one each. Which platforms
     exist is not editable: that is an icon and a piece of markup, not copy. */
  { key: 'social.spotify',   where: 'index.html', kind: 'url', max: LIMITS.url,
    group: 'Where the social buttons go', label: 'Spotify' },
  { key: 'social.youtube',   where: 'index.html', kind: 'url', max: LIMITS.url,
    group: 'Where the social buttons go', label: 'YouTube' },
  { key: 'social.instagram', where: 'index.html', kind: 'url', max: LIMITS.url,
    group: 'Where the social buttons go', label: 'Instagram' },
  { key: 'social.tiktok',    where: 'index.html', kind: 'url', max: LIMITS.url,
    group: 'Where the social buttons go', label: 'TikTok' },

  /* ── shop.html ─────────────────────────────────────────────────────────── */
  { key: 'shop.pageTitle',       where: 'shop.html', max: LIMITS.title, group: 'Shop page, details you cannot see', label: 'Browser tab and search-result title' },
  { key: 'shop.metaDescription', where: 'shop.html', max: LIMITS.meta,  group: 'Shop page, details you cannot see', label: 'Search-result description' },
  { key: 'shop.ogTitle',         where: 'shop.html', max: LIMITS.title, group: 'Shop page, details you cannot see', label: 'Title when the page is shared' },
  { key: 'shop.ogDescription',   where: 'shop.html', max: LIMITS.meta,  group: 'Shop page, details you cannot see', label: 'Description when the page is shared' },
  { key: 'shop.navRecord',       where: 'shop.html', max: LIMITS.label },
  { key: 'shop.navShop',         where: 'shop.html', max: LIMITS.label },
  { key: 'shop.eyebrow',         where: 'shop.html', max: LIMITS.label },
  { key: 'shop.heading',         where: 'shop.html', max: LIMITS.line },
  { key: 'shop.lede',            where: 'shop.html', max: LIMITS.para },
  { key: 'shop.footCredit',      where: 'shop.html', max: LIMITS.line },
  { key: 'shop.footBack',        where: 'shop.html', max: LIMITS.label },

  /* ── product.html ──────────────────────────────────────────────────────── */
  { key: 'product.pageTitle',       where: 'product.html', max: LIMITS.title, group: 'Product page, details you cannot see', label: 'Browser tab and search-result title' },
  { key: 'product.metaDescription', where: 'product.html', max: LIMITS.meta,  group: 'Product page, details you cannot see', label: 'Search-result description' },
  { key: 'product.navRecord',       where: 'product.html', max: LIMITS.label },
  { key: 'product.navShop',         where: 'product.html', max: LIMITS.label },
  { key: 'product.crumb',           where: 'product.html', max: LIMITS.label },
  { key: 'product.footCredit',      where: 'product.html', max: LIMITS.line },
  { key: 'product.footBack',        where: 'product.html', max: LIMITS.label },

  /* ── js/copy.js ────────────────────────────────────────────────────────── */
  /* Three states of the same grid, only one of which is on screen at a time —
     and the one you are looking at is almost always the products. So all three
     go in the panel, including the one that lives in the markup. */
  { key: 'shop.loading', where: 'shop.html', max: LIMITS.line,
    group: 'The shop, before and instead of the products', label: 'While the products are loading' },
  { key: 'shop.empty', where: 'js/copy.js', max: LIMITS.line,
    group: 'The shop, before and instead of the products', label: 'When there is nothing in the shop' },
  { key: 'shop.error', where: 'js/copy.js', max: LIMITS.line,
    group: 'The shop, before and instead of the products', label: 'When the shop fails to load' },

  { key: 'product.colour',    where: 'js/copy.js', max: LIMITS.label },
  { key: 'product.size',      where: 'js/copy.js', max: LIMITS.label },
  { key: 'product.add',       where: 'js/copy.js', max: LIMITS.label },
  { key: 'product.note',      where: 'js/copy.js', max: LIMITS.para },
  { key: 'product.priceFrom', where: 'js/copy.js', max: LIMITS.label },
  { key: 'product.specBrand', where: 'js/copy.js', max: LIMITS.label },
  { key: 'product.specModel', where: 'js/copy.js', max: LIMITS.label },
  { key: 'product.specType',  where: 'js/copy.js', max: LIMITS.label },

  /* Only ever seen mid-choice, or when Printful is short of something. They
     get a panel rather than a place on the page. */
  { key: 'product.loading', where: 'product.html', max: LIMITS.label,
    group: 'The product page, prompts and shortages', label: 'While the product is loading' },
  { key: 'product.choose', where: 'js/copy.js', max: LIMITS.line,
    group: 'The product page, prompts and shortages', label: 'The button before a choice is made — {what} is filled in from the three below' },
  { key: 'product.missingColour', where: 'js/copy.js', max: LIMITS.label,
    group: 'The product page, prompts and shortages', label: '{what}, when no colour is chosen' },
  { key: 'product.missingSize', where: 'js/copy.js', max: LIMITS.label,
    group: 'The product page, prompts and shortages', label: '{what}, when no size is chosen' },
  { key: 'product.missingJoin', where: 'js/copy.js', max: LIMITS.label,
    group: 'The product page, prompts and shortages', label: 'Joins the two when both are missing' },
  { key: 'product.unavailable', where: 'js/copy.js', max: LIMITS.line,
    group: 'The product page, prompts and shortages', label: 'A product with nothing available at all' },
  { key: 'product.sizeUnavailable', where: 'js/copy.js', max: LIMITS.line,
    group: 'The product page, prompts and shortages', label: 'Hover text on a size the chosen colour does not come in' },
  { key: 'product.imageNav', where: 'js/copy.js', max: LIMITS.line,
    group: 'The product page, prompts and shortages', label: 'Screen-reader label on a thumbnail — {n} and {total} are filled in' },
];

const BY_KEY = new Map(SCHEMA.map((f) => [f.key, f]));

/** The keys held in js/copy.js, in schema order. */
const jsKeys = () => SCHEMA.filter((f) => f.where === 'js/copy.js').map((f) => f.key);

/** The keys held in one of the HTML files. */
const htmlKeys = (file) => SCHEMA.filter((f) => f.where === file).map((f) => f.key);

/** Every file a save might have to rewrite. */
const FILES = [...new Set(SCHEMA.map((f) => f.where))];

/* ── Sanitising ────────────────────────────────────────────────────────────

   Applied on the way IN, at the one door that writes, and kept next to the
   schema that says what a field IS. Splitting "what a heading may contain"
   from "what a heading is" across two files is how the two stop agreeing.
   ────────────────────────────────────────────────────────────────────────── */

/* Whitespace, including the non-breaking space a browser inserts on its own
   while you type. It is a different character from the one you meant, it
   compares unequal, and so it reads as an edit nobody made. Written as an
   escape rather than as itself so it is visible in the source. */
const SPACE = /[\s ]+/g;

/**
 * Plain text: one line, trimmed, capped, control characters gone.
 *
 * Filtered by code point rather than by a regex class, because the class has
 * to spell the control range as escapes, and an editor that helpfully turns
 * those escapes back into the characters themselves leaves a literal NUL
 * sitting invisibly in the source. This cannot be got wrong by looking at it.
 *
 * @returns {string|null} null when nothing is left, which every caller reads
 *   as "leave this field alone" rather than as "set it to empty". An empty
 *   heading is never what anybody meant, and it is what a slipped keystroke
 *   in a contenteditable produces.
 */
function text(value, max = LIMITS.line) {
  if (typeof value !== 'string') return null;

  const stripped = Array.from(value)
    .filter((ch) => {
      const c = ch.codePointAt(0);
      if (c < 0x20 || c === 0x7f) return false;       // C0 controls and DEL
      if (c >= 0x200b && c <= 0x200d) return false;   // zero-width space, ZWNJ, ZWJ
      if (c === 0xfeff) return false;                 // byte-order mark
      return true;
    })
    .join('');

  const clean = stripped.replace(SPACE, ' ').trim().slice(0, max);
  return clean || null;
}

/**
 * A destination.
 *
 * http and https ONLY. `javascript:` in an href executes on click, so this is
 * an allowlist on the scheme and never a blocklist of the bad ones — a
 * blocklist is where `JavaScript:`, a leading tab and an embedded newline get
 * through, because they are all the same URL to a browser and different
 * strings to a test.
 *
 * The string is PARSED rather than pattern-matched, and that buys two things a
 * `/^https?:/` test does not. It rejects what is not a URL at all — `https://`,
 * `http://[`, `http:// example.com` all begin with a scheme we allow and are
 * none of them a link, so a prefix test puts them in the page as an href that
 * goes nowhere. And it returns a NORMALISED value, which is what lets
 * lib/content.js tell a real edit from a re-save (see the note there).
 *
 * Every editable URL on this site is a link a visitor is expected to click, so
 * there is no case for allowing a third scheme, and none for allowing a
 * relative one either: these point at other people's platforms.
 */
function url(value) {
  if (typeof value !== 'string') return null;
  const raw = value.trim().slice(0, LIMITS.url);
  if (!raw) return null;
  let parsed;
  try {
    parsed = new URL(raw);
  } catch {
    return null;                       // not a URL at all, including a relative one
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return null;
  return parsed.href;
}

/** One field, by the rules its schema entry gives it. An unknown key is null. */
function sanitise(key, value) {
  const field = BY_KEY.get(key);
  if (!field) return null;
  return field.kind === 'url' ? url(value) : text(value, field.max);
}

/**
 * Sanitise a whole incoming document, keeping only known keys that survived.
 * Anything rejected is simply absent, and an absent key means "unchanged" —
 * so a hostile or malformed field leaves no trace at all.
 */
function sanitiseAll(incoming) {
  const out = {};
  if (!incoming || typeof incoming !== 'object') return out;
  for (const [key, value] of Object.entries(incoming)) {
    const clean = sanitise(key, value);
    if (clean !== null) out[key] = clean;
  }
  return out;
}

/* ── js/copy.js, read and written ─────────────────────────────────────────── */

/**
 * Pull the object back out of the generated file.
 *
 * Between the first '{' after the assignment and the last '}' is JSON, because
 * renderClientCopy is the only thing that ever writes this file and it writes
 * JSON.stringify's output. Anything else is a file somebody has edited into a
 * shape this cannot read, and the honest answer to that is null rather than a
 * guess — the caller turns it into a refusal to save over work it cannot see.
 *
 * @returns {object|null}
 */
function readClientCopy(source) {
  if (typeof source !== 'string') return null;
  const assign = source.indexOf(OPEN);
  if (assign < 0) return null;
  const open = source.indexOf('{', assign);
  const close = source.lastIndexOf('}');
  if (open < 0 || close < open) return null;
  try {
    const parsed = JSON.parse(source.slice(open, close + 1));
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

/**
 * Write the file.
 *
 * Keys come out in schema order rather than in whatever order the browser
 * happened to send them, so a diff of this file shows the edit and not a
 * reshuffle. Only keys the schema knows are written: a save cannot grow the
 * file a field the site has no code to print.
 */
function renderClientCopy(values) {
  const ordered = {};
  for (const key of jsKeys()) {
    if (typeof values?.[key] === 'string') ordered[key] = values[key];
  }
  return `${HEADER}\n${OPEN}${JSON.stringify(ordered, null, 2)};\n`;
}

module.exports = {
  SCHEMA,
  BY_KEY,
  LIMITS,
  FILES,
  OPEN,
  jsKeys,
  htmlKeys,
  text,
  url,
  sanitise,
  sanitiseAll,
  readClientCopy,
  renderClientCopy,
};
